### GraphQL Query
POST http://localhost:8080/graphql
Content-Type: application/json

{
  "query": "query { hello(name: \"JeongMin\") }"
}

### GraphQL Mutation
POST http://localhost:8080/graphql
Content-Type: application/json

{
  "query": "mutation { createUser(name: \"Park\") }"
}
